<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\edit.png" />
    <None Remove="images\edited.png" />
    <None Remove="images\search-alt.png" />
    <None Remove="images\text.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\close.png" />
    <Resource Include="images\edit.png" />
    <Resource Include="images\edited.png" />
    <Resource Include="images\search-alt.png" />
    <Resource Include="images\text.gif" />
  </ItemGroup>

</Project>
